sudo: required
language: java
jdk: oraclejdk8

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: nursery-api

on:  
  branch: master

script: 
  - mvn clean package
  - java -jar target/nursery-api-1.0-SNAPSHOT.war
  - mvn spring-boot:run- -Dspring.profiles.active=stg