sudo: required
language: java
jdk: oraclejdk8

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: nursery-api

on:  
  branch: master
  
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: 
  - mvn clean package
  - mvn spring-boot:run -Dspring.profile.actives=stg
